tier4/tier4_perception_dataset

- perception_dataset/constants.py
- perception_dataset/utils/label_converter.py
Add `__str__` method to `LABEL_PATH_ENUM` in order to cast it into string with `str()` not `isinstance()` in `LabelConverter()`
```bash
```
> feat: add support of `__str__` method in `LABEL_PATH_ENUM`

- perception_dataset/deepen/deepen_to_t4_converter.py
- perception_dataset/t4_dataset/annotation_files_generator.py
- perception_dataset/utils/calculate_num_points.py
Support deepen to T4 format conversion for the data contains non-key-frame samples
Tested with T4 DBv1.1 dataset.
convert_deepen_to_t4.yaml:
```yaml
task: convert_deepen_to_t4
description:
visibility:
full: "No occlusion of the object."
most: "Object is occluded, but by less than 50%."
partial: "The object is occluded by more than 50% (but not completely)."
none: "The object is 100% occluded and no points/pixels are visible in the label."
camera_index:
CAM_FRONT: 0
CAM_FRONT_RIGHT: 1
CAM_BACK_RIGHT: 2
CAM_BACK: 3
CAM_BACK_LEFT: 4
CAM_FRONT_LEFT: 5
conversion:
input_base: ./data/non_annotated_t4_format
input_anno_file: ./data/deepen_format/lidar_annotations_accepted_deepen.json
input_bag_base: ./data/rosbag2
output_base: ./data/t4_format
topic_list: ./config/topic_list_xx1_perception.yaml …
```
> feat: support non key frame conversion

- README.md
Update of setup instructions after changes in ROS dependencies in the repository.
Not updated setup:
1. Setup the repository following the setup instructions from [README file in main branch](https://github.com/tier4/tier4_perception_dataset#setup).
2. [Run tests](https://github.com/tier4/tier4_perception_dataset#test)
3. You should have ```ModuleNotFoundError: No module named 'tier4_perception_msgs'```
Updated setup:
1. Setup the repository following the modified instructions from [README in this PR](https://github.com/tier4/tier4_perception_dataset/tree/docs/update-of-setup-instructions#setup) (in the new repository)
2. [Run tests](https://github.com/tier4/tier4_perception_dataset#test)
3. The tests should be passed
[Download test …
> docs: update of setup instructions

- config/add_2d_attribute.yaml
- config/label/attribute.yaml
- perception_dataset/convert.py
- perception_dataset/t4_dataset/attribute_merger.py
Add 2d attribute merger.
This merger appends 2D image attributes to an existing T4 format dataset from deepen.json.
Verify that only 2D image attributes have been added to the existing T4 dataset.
T4 dataset: https://drive.google.com/file/d/1uv-XbHTpsjgCMBwugezFxKDMd7AilrzB/view?usp=drive_link
Deepen json: https://drive.google.com/file/d/1tFSIewqeWUWcJmyh2TrpnA6cLVkQA4ha/view?usp=drive_link
(Since current Deepen json is just delivered from MAP IV, it does **not** include dataset_id. You may use one downloaded from Deepen.AI)
```bash
python -m perception_dataset.convert --config config/add_2d_attribute.yaml --overwrite 
```
Use https://github.com/tier4/AWMLtools/pull/165 with `--paint_lamp_state"` option to visualize T4 dataset.
> feat: add 2d attribute merger

- config/rosbag2_to_t4/convert_scenario_sim_to_tracking_eval.yaml
- config/rosbag2_to_t4/convert_tracking_debugger_to_tracking_eval.yaml
- config/topic_list_tracking_eval.yaml
- perception_dataset/convert.py
- perception_dataset/rosbag2/converter_params.py
- perception_dataset/rosbag2/rosbag2_to_non_annotated_t4_converter.py
- perception_dataset/rosbag2/rosbag2_to_t4_tracking_converter.py
Add tracking sim to tracking eval converter.
Make sure that the following conversion works properly.
For tracking debugger rosbag
```bash
python -m perception_dataset.convert --config config/rosbag2_to_t4/convert_tracking_debugger_to_tracking_eval.yaml
```
For scenario simulator rosbag
```bash
python -m perception_dataset.convert --config config/rosbag2_to_t4/convert_scenario_sim_to_tracking_eval.yaml
```
> feat: add tracking regression converter

- perception_dataset/rosbag2/rosbag2_to_non_annotated_t4_converter.py
- tests/test_t4_dataset_conversion.py
Correct a bug in calculating the generatable frame number
Verify that the conversion is successfully completed without any issues using a rosbag in which some topics are dropped.
```bash
python -m perception_dataset.convert --config config/convert_rosbag2_to_non_annotated_t4_sample.yaml --overwrite 
```
> fix(rosbag2_to_non_annotated_t4): frame number calc

- perception_dataset/rosbag2/rosbag2_reader.py
- perception_dataset/rosbag2/rosbag2_to_non_annotated_t4_converter.py
* fix: ensure /tf and /tf_static topics are present in Rosbag2Reader
* adjust frame timestamp comparison in _Rosbag2ToNonAnnotatedT4Converter
Ensure that the CI tests are passing.
> feat: ensure /tf and /tf_static topics are present, and adjust frame timestamp comparison

- perception_dataset/t4_dataset/keyframe_consistency_resolver.py
- tests/test_t4_dataset_conversion.py
Fix bug in https://github.com/tier4/tier4_perception_dataset/pull/38
- fix: change nbr_samples in keyframe_consistency_resolver
- test: Add timestamp assertions for ego_pose and sample_data
Please use sample test data
`poetry run pytest tests/test_t4_dataset_conversion.py`
None
None
> fix(deepen_to_t4): change nbr_samples in keyframe_consistency_resolver and add timestamp assertions in test

- config/interpolate_t4.yaml
- docs/tasks/interpolate.md
- perception_dataset/convert.py
- perception_dataset/t4_dataset/data_interpolator.py
Add support of interpolating data with a specified Hz.
Interpolation updates the following records and fields
- `scene.json`: update `nbr_samples`
- `instance.json`: update `nbr_annotations`
~- `ego_pose.json`: add new record with the interpolated `timestamp/translation/rotation`~
- `sample.json`: add new record with the interpolated `timestamp`
- `sample_data.json`: update with the corresponding `sample` and set `is_key_frame=Ture`
- `sample_annotation.json`: add new record with interpolated `translation/rotation` and the corresponding `sample`
```bash
python3 -m perception_dataset.convert --config ./config/interpolate_t4.yaml
python3 perception_dataset/t4_dataset/data_interpolator.py <DATA_ROOT>
```
> feat: add data interpolation

- perception_dataset/rosbag2/autoware_msgs.py
- perception_dataset/rosbag2/rosbag2_to_annotated_t4_tlr_converter.py
According to https://github.com/tier4/tier4_autoware_msgs/pull/112, `TrafficSignal` and `TrafficSignalArray` have been renamed into `TrafficLight` and `TrafficLightArray` respectively. This PR updates them.
```bash
```
> fix: update `TrafficSignal` to `TrafficLight`

- perception_dataset/t4_dataset/annotation_files_generator.py
This update fixes a bug in the annotation file generator for a perception dataset, where bounding boxes (bboxes) were incorrectly clipped using a shared mask for all cameras, instead of using the specific mask for each camera.
Additional info #77 
```bash
```
> fix: adjust bbox mask based on frame and sensor

- config/convert_rosbag2_to_non_annotated_t4_tlr_sample.yaml
- config/rosbag2_to_t4/convert_rosbag2_to_annotated_t4_tlr.yaml
- tests/config/convert_rosbag2_to_annotated_t4_tlr.yaml
- tests/config/convert_rosbag2_to_non_annotated_t4_tlr_test.yaml
Fix default `delay_msec` value (from 0.1 to 100) 
Must be merged with https://github.com/tier4/AWMLdataset/pull/216
Please check that all the parts are corrected regarding `delay_msec`
Default test is fine.
No ref
None
> fix(rosbag2_t4_tlr): fix default delay_msec value

- config/interpolate_t4.yaml
- docs/tasks/interpolate.md
- perception_dataset/convert.py
- perception_dataset/t4_dataset/data_interpolator.py
- modify wrong key `prev_token` to `prev` in `sample.json`
- add support of excluding to copy specified patterns which helps making copy faster
- skip copying `data`, `input_bag`, `pointcloud_map*` by default
```bash
$ python3 -m perception_dataset.convert --config ./config/interpolate_t4.yaml
```
> fix: modify key name and add option to exclude copying

- config/convert_fastlabel_2d_to_t4.yaml
- docs/tools_overview.md
- perception_dataset/convert.py
- perception_dataset/deepen/deepen_to_t4_converter.py
- perception_dataset/fastlabel_to_t4/fastlabel_2d_to_t4_converter.py
- perception_dataset/t4_dataset/annotation_files_generator.py
- perception_dataset/t4_dataset/classes/instance.py
This PR adds functionality to convert annotations from Fastlabel annotation JSON to T4 dataset. This enables conversion of annotations created in Fastlabel to T4 format.
Changes:
- Added functionality to convert annotations from FastLabel 2D annotation JSON to T4 dataset (2D only).
- Updated the documentation to include information about the new feature.
Please review that the 2D bounding boxes are correctly assigned.
Check the dataset visualization videos: https://drive.google.com/drive/u/0/folders/1dmVG76D-tLPuEc2Aa423CHXhYRY6bC3X
test data
FastLabel JSON files: https://drive.google.com/drive/folders/1k4Jp2x8LDwbrTTH-6lvmBuYOmxtJylaJ
Use with T4 dataset DBv2.0.
```bash
python -m perception_dataset.convert --config config/convert_fastlabel_2dlink_to_t4.yaml --overwrite 
```
> feat: add fastlabel-2D to t4dataset converter

- config/label/attribute.yaml
- config/merge_2d_t4dataset_to_3d.yaml
- docs/tools_overview.md
- perception_dataset/convert.py
- perception_dataset/t4_dataset/t4_dataset_2d3d_merger.py
This Pull Request introduces functionality to merge datasets from T4 containing annotations for both 2D camera images and 3D LiDAR point clouds.
The purpose of this feature is to combine annotations from different sensor modalities, specifically 2D camera images and 3D LiDAR point clouds, thereby creating comprehensive datasets suitable for tasks involving multi-sensor fusion and perception.
- Implemented a new merge functionality capable of appropriately integrating annotations from 2D camera images and 3D LiDAR point clouds to produce a unified dataset.
- Added comprehensive documentation detailing the usage of the new feature and providing insights into API specifics.
Included unit tests to ensure the correctness and robustness of the new functionality.
Please review that the 2D bboxes …
> feat: merge T4 Datasets with 2D Camera annotations and 3D LiDAR annotations

- .github/workflows/build-and-test.yaml
- README.md
- build_depends.repos
- perception_dataset/rosbag2/autoware_msgs.py
Support both `autoware_auto_msgs` and `autoware_msgs`
See the pytest results in CI.
None
None
> feat: add backward compatibility for autoware_auto_msgs and autoware_msgs

- README.md
- build_depends.repos
- perception_dataset/rosbag2/rosbag2_converter.py
- pyproject.toml
- Add `nebula` to `build_depends` and modify the build process for the `pandar_msg` package to ensure compatibility and successful compilation.
- Improve rosbag filtering by handling AttributeError exceptions, defaulting to using the record time to ensure robust operation under error conditions.
> fix `pandar_msg` dependency

- perception_dataset/rosbag2/rosbag2_to_non_annotated_t4_converter.py
Enhance the image generation process by avoiding both encoding and decoding:
It improves image conversion time. Total time to convert 500 frames of compressed image messages reduced from 20-60 seconds to 1-2 seconds on my PC.
- Avoid encoding and decoding image data; save it directly as is.
- Modify `_generate_image_data` to accept both `np.ndarray` and `CompressedImage` types.
- Introduce an `image_shape` parameter to correctly set image dimensions.
- Ensure proper saving of `CompressedImage` data.
**before**
**after** 
Please verify that the pytest passes.
> feat(rosbag_to_non_annotated_t4): Enhance image data handling to support CompressedImage format

- perception_dataset/deepen/non_annotated_t4_to_deepen_converter.py
Following error occurs for some t4dataset. This PR is to address this issue.
```bash
jt08_odaiba_2024-04-16_gen2_withpcd_sliced/data/                                                                                                                                                                   
├── CAM_BACK_LEFT                                                                                                                                                                                                  
│   ├── ...
│   ├── 00270.jpg
│   └── 00271.jpg
├── CAM_BACK_RIGHT
│   ├── ...
│   └── 00270.jpg
├── CAM_FRONT
│   ├── ...
│   └── 00270.jpg
├── CAM_FRONT_LEFT
│   ├── ...
│   └── 00270.jpg
├── CAM_FRONT_RIGHT
│   ├── ...
│   └── 00270.jpg
└── LIDAR_CONCAT
...
```
1. Download [non …
> fix(non_annotated_t4_to_deepen): skip frame when some cameras do not exist

- perception_dataset/utils/rosbag2.py
Fix intensity decoding during the conversion of rosbag2 to the non-annotated T4 format.
Use any rosbag file.
Check the intensity of pointcloud in the non-annotated t4 format dataset.
Before:
After:
```bash
python -m perception_dataset.convert --config config/convert_rosbag2_to_non_annotated.yaml --overwrite --without_compress 
```
> fix(rosbag2_to_non_annotated_t4): decoding pointcloud2 msg

- .github/workflows/push-release-tag.yml
> chore: fix push release tag workflow

- poetry.lock
- t4-devkit/docs/tutorials/render.md
- t4-devkit/pyproject.toml
- t4-devkit/t4_devkit/tier4.py
After this PR, users can save rendering result as follows:
```python
from t4_devkit import Tier4
t4 = Tier4("annotation", "<DATASET_PATH>")
scene_token = t4.scene[0].token
t4.render_scene(scene_token, save_dir="<DIR_TO_SAVE>")
```
Also, we can suspend to spawn a viewer by specifying `show=False` as below:
```python
t4.render_scene(scene_token, save_dir="<DIR_TO_SAVE>", show=False)
```
Note that, both `save_dir` and `show` are keyword-only arguments.
Check whether each rendering method works including `render_scene(...)/render_instance(...)/render_point_cloud(...)`.
[TIER IV INTERNAL LINK](https://console.data-search.tier4.jp/projects/prd_jt/t4datasets/d20b53bf-8b4e-4040-9d2c-6df22120177a?version=2)
```python
from t4_devkit import Tier4
t4 = Tier4("annotation", "<DATASET_PATH>") …
```
> feat(t4 devkit): add support of saving rendering result as `.rrd`

- perception_dataset/deepen/non_annotated_t4_to_deepen_converter.py
- pyproject.toml
Fixes a bug in the frame skipping logic that was introduced in #114, where frames were being skipped incorrectly under certain conditions. 
This fix ensures that frame skipping now functions as intended
> fix(non_annotated_t4_to_deepen): fix frame skipping logic

- perception_dataset/utils/rosbag2.py
This pull request introduces significant changes to the `point_cloud2_to_array` function in the `perception_dataset/utils/rosbag2.py` file. The modifications improve the handling of PointCloud2 messages by refactoring the code to be more modular and adding support for additional fields.
Key changes include:
Enhanced field handling:
* Added support for the `index` field, mapping it to `lidar_index` in the output dictionary.
Data filtering:
* Added a filter to remove rows where `xyz` values are all zero, ensuring cleaner data output.
> fix(rosbag2_to_non_annotated_t4): enhance point_cloud2_to_array to support optional lidar index field

- perception_dataset/fastlabel/download_annotations.py
This pull request includes a change to the `download_completed_annotations` function in the `perception_dataset/fastlabel/download_annotations.py` file. The change adds project details to each task before saving them.
Enhancements to task details:
* [`perception_dataset/fastlabel/download_annotations.py`](diffhunk://#diff-8f4c0ad8eae73929e687030b1521a4cf70e53bbaf0bd593dc46c2a4ba8ba0111R92-R94): Added `project_name`, `project_slug`, and `project_id` to each task in the `download_completed_annotations` function.
> feat (fastlabel): add project information to the label

- perception_dataset/fastlabel/download_annotations.py
This pull request includes a change to the `rename_image_task_name` function in the `perception_dataset/fastlabel/download_annotations.py` file. The change introduces additional logic to handle cases where the `base_name` does not follow a specific format.
Key change:
* [`perception_dataset/fastlabel/download_annotations.py`](diffhunk://#diff-8f4c0ad8eae73929e687030b1521a4cf70e53bbaf0bd593dc46c2a4ba8ba0111R73-R78): Added a print statement for debugging and additional logic to handle cases where `base_name` does not start with "data" and does not have exactly one "/" character.
> feat(fast_label): udpate rename_task to support TLR task name

- perception_dataset/ros2/oxts_msgs/ins_handler.py
- perception_dataset/rosbag2/rosbag2_to_non_annotated_t4_converter.py
This PR deals with the cases that `NavSatFix` message is not included in RosBag.
Before this PR, the following error has been raised in this case:
In order to deal with this problem, as of this PR, interpolation will be skipped and all `geocoordinate` fields will be filled by `None` as follows:
```json
[
{
"token": "922dd1d3795848398cd258ce6011969a",
"translation": [
6371.679376965268,
14683.198967615801,
-114.74298987091399
],
"rotation": [
-0.0011899695839468949,
0.927482095564976,
-0.3738644686696874,
0.0009515488019675177
],
"timestamp": 1724915739299722,
"twist": [
19.191881914181405,
-0.32103013858398094,
-0.285456699862336,
0.9235548267151779,
0.2642397397715217,
0.32006239842098405
],
"acceleration": [
-0.3131694334716736,
0.11359620433402622,
-10.569883635372245
], …
```
> fix: resolve ValueError if there is no observed NavSatFix messages

- perception_dataset/deepen/download_annotations.py
Minor refactoring for deepen/download_annotations
Please follow the document to run the download_annotations script.
```yaml
task: convert_deepen_to_t4
description:
visibility:
full: "No occlusion of the object."
most: "Object is occluded, but by less than 50%."
partial: "The object is occluded by more than 50% (but not completely)."
none: "The object is 90-100% occluded and no points/pixels are visible in the label."
camera_index:
CAM_FRONT: 0
CAM_FRONT_RIGHT: 1
CAM_BACK_RIGHT: 2
CAM_BACK: 3
CAM_BACK_LEFT: 4
CAM_FRONT_LEFT: 5
conversion:
input_base: ./data/non_annotated_t4_format
input_anno_file: ./data/deepen_format/hoge.json
input_bag_base: ./data/rosbag2
output_base: ./data/t4_format
topic_list: ./config/topic_list.yaml
ignore_interpolate_label: False
dataset_corresponding:
fuga: …
```
> refactor(deepen/download_annotations): minor fix for more user friendly tool

- perception_dataset/deepen/deepen_to_t4_converter.py
- perception_dataset/fastlabel_to_t4/fastlabel_2d_to_t4_converter.py
- perception_dataset/t4_dataset/annotation_files_generator.py
This pull request includes changes to the `perception_dataset` module, particularly focusing on handling surface categories in the dataset conversion process. The most important changes include importing the `yaml` module, updating the constructor and methods to handle surface categories, and modifying the annotation file generation process.
Handling surface categories:
* [`perception_dataset/deepen/deepen_to_t4_converter.py`](diffhunk://#diff-b9dca63cb1e60433c3a55405c357fd22725664db75d3fc2b60d5359f3c21f382R7): Imported the `yaml` module to handle YAML files.
* [`perception_dataset/deepen/deepen_to_t4_converter.py`](diffhunk://#diff-b9dca63cb1e60433c3a55405c357fd22725664db75d3fc2b60d5359f3c21f382R61-R65): Updated the constructor to load surface categories from a YAML file if specified in …
> feat: enhance surface category handling in AnnotationFilesGenerator and DeepenToT4Converter

- config/convert_fastlabel_to_t4.yaml
- config/label/object.yaml
- perception_dataset/convert.py
- perception_dataset/fastlabel_to_t4/fastlabel_2d_to_t4_converter.py
- perception_dataset/fastlabel_to_t4/fastlabel_to_t4_converter.py
- perception_dataset/t4_dataset/classes/object_ann.py
- perception_dataset/t4_dataset/classes/surface_ann.py
- perception_dataset/utils/transform.py
This pull request introduces a new conversion task to the `perception_dataset` module, adds new label configurations, and includes utility functions to handle rotations. The most important changes include adding a new converter class for FastLabel to T4 data, updating the conversion script to handle the new task, and enhancing the annotation loading and formatting functions.
* [`perception_dataset/fastlabel_to_t4/fastlabel_to_t4_converter.py`](diffhunk://#diff-068468d17f8f67d6f87cf8288c73b6dc5549dbaec317dfcae29013b256c32db0R1-R227): Added the `FastLabelToT4Converter` class to convert FastLabel data to T4 data, including methods to handle directory structures, annotations, and consistency checks.
* [`perception_dataset/convert.py`](diffhunk://#diff-9f732f550900ea57319170885b33866ccda788bee7 …
> feat: add FastLabel 3D to T4 format

- perception_dataset/deepen/get_annotation_status.py
- perception_dataset/deepen/import_labels.py
This pull request includes several changes to the `perception_dataset` module, focusing on adding a new script for fetching annotation statuses and improving exception handling in the `import_labels` module. The most important changes include the addition of a new script to get annotation statuses, the enhancement of the `AnnotationNotFoundException` class, and the modification of the `get_dataset_status` function to raise the custom exception.
* [`perception_dataset/deepen/get_annotation_status.py`](diffhunk://#diff-e9db2a76079a9a304d4e11902df7b44da9bf736b8ee2890878494a6ee2bec5f5R1-R43): Added a new script to fetch and log the status of datasets from a configuration file. This script uses `argparse` for command-line arguments, `yaml` for configuration file parsing, and logs the status of …
> feat(deepen): add get annotation status script

- perception_dataset/deepen/deepen_to_t4_converter.py
- perception_dataset/fastlabel_to_t4/fastlabel_2d_to_t4_converter.py
This pull request introduces parallel processing to the `fastlabel_2d_to_t4_converter.py` to improve the performance of annotation processing. The most important changes include importing necessary modules for parallel processing, refactoring the annotation formatting function, and adding new methods to handle parallel processing.
Parallel processing improvements:
* [`perception_dataset/fastlabel_to_t4/fastlabel_2d_to_t4_converter.py`](diffhunk://#diff-62be1a85945bd3f154e4f5fab6110b0c100c0ad712dd83c0b675a4875f4190c3R3): Imported `ProcessPoolExecutor` and `as_completed` from `concurrent.futures` to enable parallel processing.
* [`perception_dataset/fastlabel_to_t4/fastlabel_2d_to_t4_converter.py`](diffhunk://#diff-62be1a85945bd3f154e4f5fab6110b0c100c0ad712dd83c0b675a4875f4190c3L178-R259): …
> refactor: parallelizate fl annotation processing 

- docs/t4_format_3d_detailed.md
This PR updates documentation about the ego pose recording.
Currently, we support 2 types of retrieving ego pose, which using `/tf` or INS message, and this PR updates documentation to describe the details of them.
```bash
```
> docs: add documentation of ego pose recording

- pyproject.toml
This pull request includes a version update for the `perception-dataset` project. The version number has been incremented from `1.0.17` to `1.0.18`.
* [`pyproject.toml`](diffhunk://#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711L3-R3): Updated the version from `1.0.17` to `1.0.18`.
> chore: bump version from 1.0.17 to 1.0.18

- perception_dataset/t4_dataset/data_interpolator.py
This PR contains following changes:
- Allow any versions of T4 dataset
- Make interpolation timestamp unique to avoid error
```bash
```
> fix(interpolation): allow any versions of t4 dataset and make timestamp uinque

- config/download_fastlabel_annotations.yaml
- perception_dataset/fastlabel/download_annotations.py
This pull request includes changes to the configuration file for downloading annotations and a minor cleanup in the Python script for renaming image task names. The most important changes are:
Configuration file updates:
* [`config/download_fastlabel_annotations.yaml`](diffhunk://#diff-c77c95bb689cd7006f97398af78d86ed03a8b82158844dab709e0c6041210157L11-L13): Removed duplicate entries of `3d-lidar-bbox` to clean up the list of tasks.
Code cleanup:
* [`perception_dataset/fastlabel/download_annotations.py`](diffhunk://#diff-8f4c0ad8eae73929e687030b1521a4cf70e53bbaf0bd593dc46c2a4ba8ba0111L73): Removed a debug print statement from the `rename_image_task_name` function to clean up the code.
> fix(fastlabel/download_annotations): remove duplicated config, remove debug output

- perception_dataset/ros2/oxts_msgs/ins_handler.py
This pull request includes changes to the `perception_dataset/ros2/oxts_msgs/ins_handler.py` file to enhance the handling of navigation satellite fixes. The most important changes include importing the `NavSatStatus` message and updating the `interpolate_nav_sat_fixes` function to skip messages with a status indicating no fix.
Enhancements to navigation satellite fix handling:
* [`perception_dataset/ros2/oxts_msgs/ins_handler.py`](diffhunk://#diff-1f82a19385f01e669d0d1ab81c9e64c88406d002fc653659516595786df615acL14-R14): Added import for `NavSatStatus` from `sensor_msgs.msg`.
* [`perception_dataset/ros2/oxts_msgs/ins_handler.py`](diffhunk://#diff-1f82a19385f01e669d0d1ab81c9e64c88406d002fc653659516595786df615acR455-R456): Updated `interpolate_nav_sat_fixes` function to skip messages where …
> feat(ins_handler): ignore nav message when status is NO-FIX

- .github/workflows/build-and-test.yaml
This PR fixes CI failed with duplicated error of upload/download artifact actions by bumping their versions to the latest.
```bash
```
> ci: bump versions of actions for upload/download artifacts to the latest

- perception_dataset/deepen/deepen_to_t4_converter.py
- perception_dataset/fastlabel_to_t4/fastlabel_2d_to_t4_converter.py
- perception_dataset/fastlabel_to_t4/fastlabel_2d_to_t4_updater.py
- perception_dataset/fastlabel_to_t4/fastlabel_to_t4_converter.py
- perception_dataset/rosbag2/rosbag2_to_non_annotated_t4_converter.py
This pull request includes several changes to the logging levels in various `convert` methods across different files. Specifically, it changes the logging level from `error` to `warning` when an output directory already exists.
Changes to logging levels:
* [`perception_dataset/deepen/deepen_to_t4_converter.py`](diffhunk://#diff-b9dca63cb1e60433c3a55405c357fd22725664db75d3fc2b60d5359f3c21f382L106-R106): Changed logging level from `error` to `warning` when the output directory already exists.
* [`perception_dataset/fastlabel_to_t4/fastlabel_2d_to_t4_converter.py`](diffhunk://#diff-62be1a85945bd3f154e4f5fab6110b0c100c0ad712dd83c0b675a4875f4190c3L80-R80): Changed logging level from `error` to `warning` when the output directory already exists.
* …
> refactor: change error log to warning when output directory exists

- perception_dataset/fastlabel/download_annotations.py
This pull request includes changes to the `perception_dataset/fastlabel/download_annotations.py` file to improve code readability and reordering of operations in the `get_labels` function. The most important changes include reformatting the return statement of the `split_project_pcd_image` function and reordering the task processing blocks in the `get_labels` function.
Code readability improvements:
* Reformatted the return statement of the `split_project_pcd_image` function to improve readability. (`perception_dataset/fastlabel/download_annotations.py`)
Reordering of operations:
* Moved the processing blocks for `cuboid` and `segmentation` tasks to a different position within the `get_labels` function to ensure consistent ordering of task processing. …
> chore(fastlabel): change download order

- perception_dataset/rosbag2/converter_params.py
- perception_dataset/rosbag2/rosbag2_to_non_annotated_t4_converter.py
I'm integrating Rosbag2ToNonAnnotatedT4Converter to our system on cloud, and the system must show why conversions fail to our users.
Rosbag2ToNonAnnotatedT4Converter does not raise any exepction when it failed.
I added raise_exception option to Rosbag2ToNonAnnotatedT4Converter. if it is true, Rosbag2ToNonAnnotatedT4Converter can raise a exception in conversions.
Rosbag2ConverterParams is common params for various converters. 
As of right now, some converters raise a exception, and some raise no exception.
How can I change other converters?
I develops on Mac, so I can't run ros2 local.
I run test on data search annotation pipeline. Should I shrare it's result?
Or should I add test codes?
```bash
```
> feat: raise exception option in rosbag2_to_non_annotated_t4

- perception_dataset/rosbag2/rosbag2_to_annotated_t4_tlr_converter.py
This PR fixes a bag related to the return value of the function called `self._generate_calibrated_sensor(...)`.
This function returns `calirabted_sensor_token` and `camera_info` in the case of sensor modality is camera.
This PR fixes bug by unpacking return value explicitly.
```bash
```
> fix: receive token and camera info in case of sensor is camera

- config/rosbag2_to_t4/convert_rosbag2_to_planning_control_evaluation.yaml
This PR adds a conversion config for the planning control team to generate the t4 dataset used for driving log replayer test.
It uses the same converter as localization_evaluation.
```bash
```
> chore(rosbag2_to_t4): add a conversion config for planning control team

- perception_dataset/ros2/oxts_msgs/ins_handler.py
**Fix INS Rotation Correction in `INSHandler`**
This PR updates the temporary rotation correction logic in `INSHandler` to properly adjust the INS output.
**Changes:**
- Apply a tentative correction to roll and yaw angles to compensate for incorrect INS driver output
- Convert current rotation from quaternion to Euler angles (`xyz` order)
- Adjust yaw (`-π/2`) and roll (`+π`) to align with the expected coordinate frame
- Update `current_rotation` with the corrected transformation
- Invert `current_twist.angular.z` and `current_acceleration[1]` to match the correct orientation
**Note:**
This is a temporary fix. If the INS driver is updated to provide correct outputs, this correction should be removed.
> fix: INS rotation correction logic to use proper Euler transformation

- perception_dataset/rosbag2/rosbag2_to_non_annotated_t4_converter.py
This PR moves the import statements of `INSHandler` and `VehicleStatusHandler` inside conditional blocks within the `_Rosbag2ToNonAnnotatedT4Converter` class.  
This avoids importing unnecessary modules when the corresponding features (`with_ins`, `with_vehicle_status`) are disabled.
- Removed top-level imports of:
- `INSHandler` from `oxts_msgs.ins_handler`
- `VehicleStatusHandler` from `vehicle_msgs.vehicle_status_handler`
- Moved these imports inside conditional blocks where `with_ins` or `with_vehicle_status` is checked.
- This change prevents module import errors or unused dependencies in environments where INS or vehicle status data are not needed.
> refactor(rosbag2_to_non_annotated_t4): move INS and vehicle status imports inside conditional blocks to avoid unnecessary dependencies

- perception_dataset/constants.py
The current cameras positions are not enough for larger vehicles like buses with 11+ cameras for certain positions.
This PR Adds two more camera positions for longer-form vehicles like buses that have top cameras located along of the length of the vehicle, and facing sideways.
> feat: support top left and right center cameras facing directly sideways

- pyproject.toml
This pull request includes a version bump for the `perception-dataset` package in the `pyproject.toml` file. The version has been updated from `1.0.22` to `1.0.23`.
> chore: bump version from 1.0.22 to 1.0.23

- config/convert_rosbag2_to_non_annotated_t4_drs_10hz.yaml
- perception_dataset/rosbag2/converter_params.py
- perception_dataset/utils/misc.py
This pull request introduces updates to configuration files and the `Rosbag2ConverterParams` class to enhance the handling of sensor data and streamline parameter initialization. The changes include adjustments to camera sensor configurations, the addition of a new configuration file, and improved initialization logic for scan periods.
* **New Configuration File:**
Added `config/convert_rosbag2_to_non_annotated_t4_drs_10hz.yaml`
* **Automatic Camera Scan Period Initialization:**
Modified the `Rosbag2ConverterParams` class in `perception_dataset/rosbag2/converter_params.py` to automatically set `camera_scan_period_sec` to `system_scan_period_sec` if the former is not provided, simplifying parameter setup.
> feat: add drs 10hz conversion config, fix camera_scan_period_sec default value params

- tests/utils/test_misc.py
This PR adds comprehensive test coverage for the `get_lidar_camera_frame_info_async` function to handle various edge cases in sensor timestamp alignment.
- Added `test_camera_20fps_lidar_10fps` for typical 2:1 frame rate synchronization
- Added parameterized test `test_lidar_camera_edge_cases` covering:
- Missing intermediate LiDAR frames
- Missing Camera frames
- Both Camera and LiDAR frame losses
> test: add tests for LiDAR and Camera frame synchronization

- perception_dataset/rosbag2/rosbag2_to_non_annotated_t4_converter.py
- perception_dataset/utils/misc.py
- pyproject.toml
- tests/utils/test_misc.py
This PR enhances the logic for generating file indices and synchronizing LiDAR and camera frames in asynchronous sensor setups.
- Introduced `_make_file_index_func()` to:
- Dynamically generate file indices depending on camera-LiDAR sync mode.
- Add suffixes (e.g., `00010-01`) for unmatched camera frames to avoid filename collisions.
- Updated `get_sample_data_filename()` to support both `int` and `str` types for frame indices.
- Improved `get_lidar_camera_frame_info_async()` to:
- Correctly handle dropped or unmatched initial camera frames.
- Keep accurate image frame indexing by introducing an offset.
- Improve debug logging with actual LiDAR frame indices.
- Added `test_first_camera_frame_dropped()` to verify correct indexing when the first camera frames are not matched to LiDAR.
- …
> fix(convert_rosbag2_to_non_annotated_t4): index alignment for image-LiDAR synchronization and improve robustness of timestamp pairing

- perception_dataset/utils/label_converter.py
- Refactored the label conversion process (`convert_label`) to use `dict.get` for fallback.
- Now, if a label is not found in the mapping, the original label is returned, preventing exceptions.
- Updated the `convert_label` method in `label_converter.py` to use `self.label_map.get(label, label)`.
- Improved code readability and robustness.
- All existing unit tests pass.
- Confirmed that passing a label not in the mapping returns the original label without raising an exception.
> refactor(label_converter): use dict.get for label conversion fallback

- perception_dataset/constants.py
Added 4 new wide-angle camera channel definitions to SENSOR_ENUM:
- `CAM_FRONT_LEFT_WIDE`
- `CAM_FRONT_RIGHT_WIDE`
- `CAM_BACK_LEFT_WIDE`
- `CAM_BACK_RIGHT_WIDE`
I have downloaded T4 datatset [(ID:cbf88fa3)](cbf88fa3-f9ea-46ba-ad52-75f4e0364e0a) and used the ros bag file under `input_bag` as the input.
I have created the following config file:
```
task: convert_rosbag2_to_non_annotated_t4
description:
scene: ""
conversion:
input_base: /home/npc2301030/.webauto/data/data/annotation_dataset/cbf88fa3-f9ea-46ba-ad52-75f4e0364e0a/0/
output_base: ./data/non_annotated_t4_format
skip_timestamp: 0.0
num_load_frames: 0
start_timestamp_sec: 0.0
accept_frame_drop: True
undistort_image: True
lidar_sensor:
topic: /sensing/lidar/concatenated/pointcloud
channel: LIDAR_CONCAT
camera_sensors:
- topic: …
```
> feat: support front/back left and right wide cameras

- perception_dataset/rosbag2/rosbag2_to_non_annotated_t4_converter.py
- perception_dataset/utils/rosbag2.py
This PR adds try/except when import ConcatenatedPointCloudInfo and ConcatenatedPointCloudInfo to use old rosbag in TLR.
In TLR, we sometimes use old rosbag. But current implementation import the new msg module. Actually, in TLR part only use it as type hint. So it is okay to not import it in there.
```bash
```
> feat(traffic_light): add try/except for adopting new msg
