tier4/tier4_perception_dataset

docs/t4_format_3d_detailed.md
- replace `our paper` with `the paper`
- correct layout
Verify document modifications
No testing is required as it is only a modification of the document
```bash
```
=> fix: t4 format 3d detailed

docs/t4_format_3d_detailed.md
Add a sample dataset link to the document.
No tests
=> feat: add sample dataset link

docs/tools_overview.md
Added section on rosbag2 pre-processing
please review pre-process command
no need
```bash
```
=> docs: add rosbag2 pre process

docs/t4_format_3d_detailed.md
Add description about category name in t4 format dataset
Ensure documentation and t4 format actual values are consistent
No test since no change in source code.
=> docs: update t4 format category name

config/rosbag2_to_t4/convert_pseudolabel_lidar.yaml, docs/tools_overview.md
* Fix instruction about pseudo-labeling (rosbag to t4 format)
* Add sample config for pseudo-labeling conversion
```bash
```
=> fix: instruction about pseudo-labeling

pyproject.toml
=> chore(release): v1.0.1

README.md
Add installation of https://github.com/ros-perception/radar_msgs, because they are required for example [here](https://github.com/tier4/tier4_perception_dataset/blob/9a05165fe150d5bd62ed3f3242c07b2f0b2b08cd/perception_dataset/rosbag2/rosbag2_to_non_annotated_t4_converter.py#L14).
```bash
```
=> docs(readme): install radar-msgs

.github/workflows/build-and-test.yaml, README.md, config/rosbag2_to_t4/convert_synthetic_data.yaml, docs/tools_overview.md, perception_dataset/rosbag2/autoware_msgs.py, perception_dataset/rosbag2/converter_params.py, perception_dataset/rosbag2/rosbag2_to_t4_converter.py, tests/config/convert_synthetic_data.yaml, tests/rosbag2/test_rosbag2_converter.py
- replace test data with old autoware perception msg (DynamicObjectArray) to the new one (TrackedObjects)
- remove implementatoins related to the old msg
confirm all tests are passed.
```bash
```
=> feat: remove old autoware perception msgs

pyproject.toml
=> chore(release): v1.0.2

perception_dataset/t4_dataset/annotation_files_generator.py
Add small change in deepen_to_t4_conversion
Make sure that all tests have passed.
=> feat(deepen_to_t4): add annotation data index check

perception_dataset/rosbag2/autoware_msgs.py
Update mapping to support added classes.
```bash
```
=> feat: update synthetic data mapping

pyproject.toml
=> chore(release): v1.0.3

perception_dataset/rosbag2/rosbag2_to_non_annotated_t4_converter.py
Fix a bug in https://github.com/tier4/tier4_perception_dataset/pull/55
Review modification in code
No test data provided
None
None
=> fix(rosbag_to_non_annotated_t4): fix non initialized variable

poetry.lock, pyproject.toml
=> chore(release): v1.0.4

pyproject.toml
=> chore(release): v1.0.5 

perception_dataset/deepen/deepen_to_t4_converter.py
to change type hints of `input_bag_base` to match the implementation
to check pass all tests
```bash
```
=> chore(deepent_to_t4): fix type hints of input_bag_base

pyproject.toml
Please check that the pytest succeeds.
=> chore(release): v1.0.6

perception_dataset/t4_dataset/classes/abstract_class.py, perception_dataset/t4_dataset/classes/attribute.py, perception_dataset/t4_dataset/classes/calibrated_sensor.py, perception_dataset/t4_dataset/classes/category.py, perception_dataset/t4_dataset/classes/ego_pose.py, perception_dataset/t4_dataset/classes/instance.py, perception_dataset/t4_dataset/classes/log.py, perception_dataset/t4_dataset/classes/map.py, perception_dataset/t4_dataset/classes/object_ann.py, perception_dataset/t4_dataset/classes/sample.py, perception_dataset/t4_dataset/classes/sample_annotation.py, perception_dataset/t4_dataset/classes/sample_data.py, perception_dataset/t4_dataset/classes/scene.py, perception_dataset/t4_dataset/classes/sensor.py, perception_dataset/t4_dataset/classes/surface_ann.py, perception_dataset/t4_dataset/classes/visibility.py
Changes allow the user to better track the fields of conrete Records and function return types.
Before:
After:
Return type is properly inferred
Fields are accesible
```bash
```
=> feat: adjusted typing

.github/workflows/build-and-test.yaml, .github/workflows/cancel-privious-workflows.yaml, .github/workflows/github-release.yaml, .github/workflows/pre-commit.yml, .github/workflows/semantic-pull-request.yaml
=> ci: add workflow timeout

pyproject.toml
=> chore(release): v1.0.7

pyproject.toml
Please check that the pytest succeeds.
=> chore(release): v1.0.8

perception_dataset/rosbag2/rosbag2_reader.py, perception_dataset/rosbag2/rosbag2_to_non_annotated_t4_converter.py, perception_dataset/rosbag2/rosbag2_to_t4_tracking_converter.py
- Simplify preprocessing by skipping full traversal of rosbags, improving processing speed in Rosbag2ToNonAnnotatedT4Converter.
- Fix typo (TracingConversion -> TrackingConversion)
Please verify that the pytest passes.
=> chore: Speed up preprocessing for rosbag loading in Rosbag2ToNonAnnotatedT4Converter

config/convert_rosbag2_to_non_annotated_t4_sample.yaml, config/convert_rosbag2_to_non_annotated_t4_tlr_sample.yaml, config/convert_rosbag2_to_non_annotated_t4_with_radar_sample.yaml, perception_dataset/rosbag2/rosbag2_reader.py, perception_dataset/rosbag2/rosbag2_to_non_annotated_t4_converter.py, tests/config/convert_rosbag2_to_non_annotated_t4.yaml
This enables
- select coordinate systems other than the map for the ego
Confirm that the tests are passing.
=> feat(rosbag_to_non_annotated_t4): add support for selecting world frame-id

perception_dataset/rosbag2/autoware_msgs.py
Reverts tier4/tier4_perception_dataset#104
=> Revert "feat: add backward compatibility for autoware_auto_msgs"

perception_dataset/rosbag2/converter_params.py
Converter params failed due to the the change in the parameter file structure in https://github.com/tier4/tier4_perception_dataset/pull/58 (invoked by pydantic validation)
Please verify that the modification is as intended
None
None
None
=> fix(converter_params): fix type

perception_dataset/rosbag2/rosbag2_converter.py, perception_dataset/utils/rosbag2.py, pyproject.toml
Fix rosbag timestamp for `/tf_static` topic
Confirm that all tests pass.
=> fix: rosbag conversion

pyproject.toml
=> chore: release v1.0.12

t4-devkit/t4_devkit/common/geometry.py, t4-devkit/tests/common/test_geometry.py
- Remove unexpected point normalization in `view_poitns(...)`.
- Refactoring distortion coefficients and assign to specific variables referred to https://github.com/tier4/AWMLtools/blob/50c5f780a2c8657a5f5b9eff4a1b73512ad2ecf1/t4dataset_tools/t4dataset_tools/visualize_lidar_projected_camera.py#L206-L235.
```bash
```
=> fix(t4-devkit): resolve unexpected point normalization

README.md
As mentioned in https://github.com/tier4/tier4_perception_dataset/pull/129, the tests were not working, due to the installation instructions being outdated.
In this PR I just copied the CI/CD steps into the documentation
```bash
```
=> chore: updated installation instructions 

pyproject.toml
=> chore: Release v1.0.17

docs/tools_overview.md
Replace autoware_auto_msgs with autoware_msgs.
```bash
```
=> docs(tools_overview): remove autoware_auto_msgs

.github/workflows/build-and-test.yaml
This PR addresses CI error in `build-and-test` as below:
```shell
=================================== FAILURES ===================================
___________________________ launch tests: smoke_test ___________________________
===========================================================
FAIL: smoke_test.TestCorrectStartup.test_wait_for_startup_then_shutdown
-----------------------------------------------------------
Exception: Launch stopped before the active tests finished.
===========================================================
FAIL: smoke_test.TestCleanShutdown.test_exit_code
-----------------------------------------------------------
Exception: Launch stopped before the active tests finished.
----------------------------- Captured stdout call -----------------------------
[DEBUG] …
```
=> ci: specify pytest target directory

pyproject.toml
This pull request includes a version update to the `perception-dataset` project.
* [`pyproject.toml`](diffhunk://#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711L3-R3): Updated the version from `1.0.18` to `1.0.19`.
=> chore: bump version from 1.0.18 to 1.0.19

perception_dataset/utils/logger.py
This PR improves the logging format for better readability in the console.
- Replaced `CustomTextFormatter()` function with a `CustomTextFormatter` class.
- Colored log output in the terminal:
- **Errors** are shown in **red**.
- **Warnings** are shown in **orange**.
- Improved log format for better visibility:
- Includes `filename`, `function name`, and `line number`.
- Easier to notice errors and warnings at a glance during development or debugging.
=> chore(logger): simplify logger text format

perception_dataset/deepen/deepen_to_t4_converter.py, perception_dataset/fastlabel_to_t4/fastlabel_to_t4_converter.py, perception_dataset/utils/logger.py
**PR Description:**
This PR introduces two key changes to improve data handling and processing:
1. **Custom Data Copying for T4 Format**:  
- Updated the `_copy_data` method to implement custom logic for copying data specific to the T4 format.
- Ensures that only relevant files (`annotation`, `data`, `status.json`) are copied, and in case the `anonymized_data` directory exists, it overwrites the original `data` directory.
2. **Skipping Datasets Not in Annotation JSONs**:  
- Added a check to skip datasets that are not present in the annotation JSONs, logging a warning for each skipped dataset.
- Ensures that only datasets with valid annotations are processed further, improving robustness and error handling during the conversion process.
These changes enhance the flexibility and robustness …
=> feat(fastlabel_to_t4): update fl 3d conversion

pyproject.toml
This pull request includes a version update to the perception-dataset project.
Updated the version from 1.0.20 to 1.0.21.
=> chore: bump version from 1.0.20 to 1.0.21

perception_dataset/t4_dataset/annotation_files_generator.py, perception_dataset/t4_dataset/classes/category.py
Add unpainted class to lidarseg and make sure all category name lowercase in category.json
=> fix(lidarseg): Add unpainted class to lidarseg
